
name: npm package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npx nx run-many --target=test --all
      - run: npx nx run-many --target=build --all

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npx nx run-many --target=build --all
      - run: npx nx run-many --target=publish --all
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
